In [1]:
import numpy as np

In [ ]:
data1 = [3.5, 5, 6, 2] # list
arr1 = np.array(data1) # array1 

In [4]:
arr1

array([3.5, 5. , 6. , 2. ])

In [30]:
data2 = (4, 5, 3.2, 7) # tuple
arr2 = np.array(data2)

In [33]:
arr2

array([4. , 5. , 3.2, 7. ])

In [7]:
arr1.ndim # array1 ning o'lchami

1

In [8]:
arr2.ndim # array2 ning o'lchami

1

In [9]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]] # list ichidagi list (nested list)
arr3 = np.array(data3) # array3

In [10]:
arr3.ndim # array3 ning o'lchami

2

In [17]:
data4 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 0, 10, 11]]
arr4 = np.array(data3) # array3

In [18]:
arr4.ndim

2

In [19]:
arr3.shape # qator va ustunlar sonini ko'rsatadi

(2, 4)

In [20]:
arr3.size # array3 ning elementlar soni

8

In [21]:
arr4.shape

(2, 4)

In [22]:
arr5 = np.zeros(shape =(2, 4)) # barcha elementlari 0 ga teng (2, 4)
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
arr6 = np.ones((2, 4)) # barcha elementlari 1 ga teng bo'lgan (2, 4)
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
arr7 = np.arange(4, 20, 2) # 4 dan 20 gacha bo'lgan qiymatlarni 2 qadam bilan massivga joylab beradi
arr7

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
arr8 = np.arange(20) # 0 dan 20 gacha bo'lgan qiymatlarni 1 qadam bilan massivga joylab beradi
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

https://colab.research.google.com/drive/1XOQHmRKcuhHbHLaY1ybGUxy14yl7z9Zf?authuser=1#scrollTo=x-L1Q8jkgrQY