In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [3]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [4]:
arr1.dtype

dtype('float64')

In [5]:
arr2.dtype

dtype('int32')

In [6]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [7]:
arr.dtype

dtype('int64')

In [8]:
float_array = arr.astype(np.float64)
float_array

array([1., 2., 3., 4.])

In [9]:
float_array.dtype

dtype('float64')

In [11]:
data = np.array([3.4, 5,7, 1.8, 4])
data

array([3.4, 5. , 7. , 1.8, 4. ])

In [12]:
data.dtype

dtype('float64')

In [13]:
int_data = data.astype(np.int64)
int_data

array([3, 5, 7, 1, 4])

In [14]:
int_data.dtype

dtype('int64')