In [1]:
import numpy as np

In [6]:
arr = np.arange(10, 100, 10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [7]:
arr[0]

np.int64(10)

In [11]:
arr[3:5]

array([40, 50])

In [13]:
sliced_arr = arr[3:5]
sliced_arr[:] = 0
sliced_arr

array([0, 0])

In [14]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [15]:
arr1 = np.arange(10, 100, 10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
sliced_arr1 = arr[3:5].copy()
sliced_arr1[:] = 0
sliced_arr1

array([0, 0])

In [17]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr2d[1, 1]

np.int64(5)

In [ ]:
arr2d[2, ]

IndexError: index 3 is out of bounds for axis 0 with size 3