In [1]:
import numpy as np
import pandas as pd

In [3]:
arr = np.array([[1, 2], [3, 4]])
print(arr)

[[1 2]
 [3 4]]


In [4]:
transposed = arr.T
print(transposed)

[[1 3]
 [2 4]]


In [5]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [6]:
transposed1 = np.transpose(arr1)
print(transposed1)

[[1 4]
 [2 5]
 [3 6]]


In [7]:
arr2 = np.array([[[1, 2], [3, 4]]])
print(arr2)

[[[1 2]
  [3 4]]]


In [8]:
swapped = np.swapaxes(arr2, 0, 1)
print(swapped)

[[[1 2]]

 [[3 4]]]


In [9]:
arr3 = np.arange(24).reshape(2, 3, 4)
print(arr3.shape)

(2, 3, 4)


In [10]:
transposed3 = np.transpose(arr3, (1, 0, 2))
print(transposed3)

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
