In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

In [3]:
print(a + b)                # element-wise addition
print(np.add(a, b)) # equivalent using function

[11 22 33 44]
[11 22 33 44]


In [4]:
print(b - a)                 # element-wise subtraction
print(np.subtract(b, a))

[ 9 18 27 36]
[ 9 18 27 36]


In [5]:
print(a * b)                 # element-wise multiplication
print(np.multiply(a, b))

[ 10  40  90 160]
[ 10  40  90 160]


In [6]:
print(b / a)                 # element-wise division
print(np.divide(b, a))

[10. 10. 10. 10.]
[10. 10. 10. 10.]


In [7]:
print(a ** 2)               # a ni kvadrat qilish
print(np.power(a, 3)) # a ni kubga oshirish

[ 1  4  9 16]
[ 1  8 27 64]


In [8]:
print(b % a)
print(np.mod(b, a))

[0 0 0 0]
[0 0 0 0]


In [9]:
print(b // a)
print(np.floor_divide(b, a))

[10 10 10 10]
[10 10 10 10]


In [10]:
print(a + 5)                # har bir elementga 5 qo‘shiladi
print(b * 2)                # har bir element 2 ga ko‘payadi

[6 7 8 9]
[20 40 60 80]


In [11]:
print(np.mean(a))
print(np.max(b))
print(np.min(a))
print(np.sum(a))

2.5
40
1
10
