In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])

In [3]:
print(a + 5)
print(a - 2)
print(a * 10)
print(a ** 2)
print(a / 2)

[ 6  7  8  9 10]
[-1  0  1  2  3]
[10 20 30 40 50]
[ 1  4  9 16 25]
[0.5 1.  1.5 2.  2.5]


In [4]:
print("Yig'indisi:", np.sum(a))
print("O'rtachasi:", np.mean(a))
print("Median:", np.median(a))
print("Minimum:", np.min(a))
print("Maximum:", np.max(a))
print("Standart og'ish:", np.std(a))

Yig'indisi: 15
O'rtachasi: 3.0
Median: 3.0
Minimum: 1
Maximum: 5
Standart og'ish: 1.4142135623730951
